### ISSUE TITLE
Great docs!

### ISSUE THREAD

**Issue by yuchi** [inakiabt/titaniumified-module-tester#1]
Can I place a link to this content in the Titaniumifier Wiki?

**Comment by inakiabt** [comment]
Sure!
I've just finished the initial commit and finally renamed it to `ti-module-tester`.
I'll be trying to explain a bit deeper in how it works. I'm not sure if it's enough.

Your opinion is welcome ;)

BTW, great work with `titaniumifier`.

**Comment by yuchi** [comment]
Done: https://github.com/smclab/titaniumifier/wiki/Testing

I’d like that page to include some information too, so consider that page as yours ;)

**Comment by inakiabt** [comment]
I was thinking that would be very cool to have something like this "tester" built-in in `titaniumifier`.

``` bash
# path/to/module
$ titaniumifier test
```

:+1: 

I'd like to have some free time to send a pull-request.
