### ISSUE TITLE
Try ti-exit

### ISSUE THREAD

**Issue by inakiabt** [inakiabt/titaniumified-module-tester#2]
Running commands in two terminals or press `CTRL+C` when app is running is annoying.
This module maybe could help to exit the iOS app from Titanium.

**Comment by yuchi** [comment]
Also have a look at the `success/failure` configuration properties of `grunt-titanium`.

Thery’re there exactly for this :)

**Comment by inakiabt** [comment]
I could make a simple hack using `success` feature in `grunt-titanium` and it worked as expected.
Thanks!
