### ISSUE TITLE
Error in grunt command

### ISSUE THREAD

**Issue by etruta** [inakiabt/titaniumified-module-tester#3]
Following step-by-step in README, in `$ grunt` command this error is shown:

```
>> Error: Unable to read "../package.json" file (Error code: ENOENT).
Warning: Task "default" not found. Use --force to continue.
```

**Comment by inakiabt** [comment]
In order to create/build a module with `titaniumifier` you must have a `package.json` defined: https://github.com/smclab/titaniumifier/wiki/Anatomy-of-a-project
That's what `ti-module-tester` needs to build your module in the process.

**Comment by etruta** [comment]
Wow... Now I understood. This `ti-module-test` is to stay inside my `titaniumifier` project.

My bad!

**Comment by inakiabt** [comment]
Or you can place it wherever you want and run `grunt --module-dir /path/to/your/module` :+1:
